// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20260925170528_InitialCompanySetup")]
    partial class InitialCompanySetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyService", b =>
                {
                    b.Property<int>("CompaniesCompany_ID")
                        .HasColumnType("int");

                    b.Property<int>("ServicesService_ID")
                        .HasColumnType("int");

                    b.HasKey("CompaniesCompany_ID", "ServicesService_ID");

                    b.HasIndex("ServicesService_ID");

                    b.ToTable("CompanyService");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Borrows", b =>
                {
                    b.Property<int>("Borrows_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Borrows_ID"));

                    b.Property<DateTime>("Borrowing_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Borrowing_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Borrowing_start_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("History")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Items_owned_by_company_ID")
                        .HasColumnType("int");

                    b.HasKey("Borrows_ID");

                    b.HasIndex("Employee_ID");

                    b.HasIndex("Items_owned_by_company_ID");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Child", b =>
                {
                    b.Property<int>("Child_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Child_ID"));

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Child_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Company", b =>
                {
                    b.Property<int>("Company_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_ID"));

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Company_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Costumer", b =>
                {
                    b.Property<int>("Costumer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Costumer_ID"));

                    b.Property<string>("Contact_e_mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contact_phone_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Service_ID")
                        .HasColumnType("int");

                    b.HasKey("Costumer_ID");

                    b.HasIndex("Employee_ID")
                        .IsUnique()
                        .HasFilter("[Employee_ID] IS NOT NULL");

                    b.HasIndex("Service_ID");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Property<int>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_ID"));

                    b.Property<int?>("Child_ID")
                        .HasColumnType("int");

                    b.Property<string>("Contact_e_mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contact_phone_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Costumer_ID")
                        .HasColumnType("int");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Employee_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.HealthCare", b =>
                {
                    b.Property<int>("HealthCare_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthCare_ID"));

                    b.Property<string>("Absentee_reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("History")
                        .HasColumnType("datetime2");

                    b.HasKey("HealthCare_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("HealthCares");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Intranet", b =>
                {
                    b.Property<int>("Intranet_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Intranet_ID"));

                    b.Property<int?>("Borrows_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Company_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Intranet_ID");

                    b.HasIndex("Borrows_ID");

                    b.HasIndex("Company_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Intranets");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Items_owned_by_company", b =>
                {
                    b.Property<int>("Items_owned_by_company_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Items_owned_by_company_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Items_owned_by_company_ID");

                    b.ToTable("Items_owned_by_company");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Rank", b =>
                {
                    b.Property<int>("Rank_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rank_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Employee_ID")
                        .HasColumnType("int");

                    b.HasKey("Rank_ID");

                    b.HasIndex("Employee_ID");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Service", b =>
                {
                    b.Property<int>("Service_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Service_ID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.Property<int>("EmployeesEmployee_ID")
                        .HasColumnType("int");

                    b.Property<int>("ServicesService_ID")
                        .HasColumnType("int");

                    b.HasKey("EmployeesEmployee_ID", "ServicesService_ID");

                    b.HasIndex("ServicesService_ID");

                    b.ToTable("EmployeeService");
                });

            modelBuilder.Entity("CompanyService", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesCompany_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesService_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Borrows", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("Borrows")
                        .HasForeignKey("Employee_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Items_owned_by_company", "ItemsOwnedByCompany")
                        .WithMany("Borrows")
                        .HasForeignKey("Items_owned_by_company_ID");

                    b.Navigation("Employee");

                    b.Navigation("ItemsOwnedByCompany");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Child", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("Children")
                        .HasForeignKey("Employee_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Company", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("Companies")
                        .HasForeignKey("Employee_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Costumer", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithOne("Costumer")
                        .HasForeignKey("DatabaseTask.Core.Domain.Costumer", "Employee_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DatabaseTask.Core.Domain.Service", null)
                        .WithMany("Costumers")
                        .HasForeignKey("Service_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.HealthCare", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("HealthCares")
                        .HasForeignKey("Employee_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Intranet", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Borrows", "Borrows")
                        .WithMany()
                        .HasForeignKey("Borrows_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Company", "Company")
                        .WithMany("Intranets")
                        .HasForeignKey("Company_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("Intranets")
                        .HasForeignKey("Employee_ID");

                    b.Navigation("Borrows");

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Rank", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", "Employee")
                        .WithMany("Ranks")
                        .HasForeignKey("Employee_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeService", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmployee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesService_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Company", b =>
                {
                    b.Navigation("Intranets");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Navigation("Borrows");

                    b.Navigation("Children");

                    b.Navigation("Companies");

                    b.Navigation("Costumer");

                    b.Navigation("HealthCares");

                    b.Navigation("Intranets");

                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Items_owned_by_company", b =>
                {
                    b.Navigation("Borrows");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Service", b =>
                {
                    b.Navigation("Costumers");
                });
#pragma warning restore 612, 618
        }
    }
}
