// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    partial class DatabaseTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Aircraft", b =>
                {
                    b.Property<Guid>("Aircraft_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Flight_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seat_Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_Of_Manufaceture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Aircraft_ID");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airline", b =>
                {
                    b.Property<Guid>("Airline_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Flight_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Airline_ID");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.Property<Guid>("Airport_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Airline_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Baggage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passenger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Terminal_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Airport_ID");

                    b.HasIndex("Airline_ID");

                    b.HasIndex("Terminal_ID");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Baggage", b =>
                {
                    b.Property<Guid>("Baggage_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Baggage_Tag_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baggage_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Baggage_ID");

                    b.ToTable("Baggages");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Employee_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Employee_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Terminal_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Terminal_ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.Property<Guid>("Flight_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Arrival_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Arrival_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Departure_Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightStatus_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Flight_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Passanger_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Flight_ID");

                    b.HasIndex("FlightStatus_ID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.FlightStatus", b =>
                {
                    b.Property<Guid>("FlightStatus_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Flight_status_change")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_change")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightStatus_ID");

                    b.ToTable("FlightStatuses");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.Property<Guid>("Gate_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Flight_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gate_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("max_aircraft_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("min_aircraft_size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gate_ID");

                    b.HasIndex("Flight_ID");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passanger", b =>
                {
                    b.Property<Guid>("Passanger_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Baggage_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date_Of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Flight_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identification_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Registration_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Registration_ID1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Passanger_ID");

                    b.HasIndex("Baggage_ID");

                    b.HasIndex("Flight_ID");

                    b.HasIndex("Registration_ID1");

                    b.ToTable("Passangers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registration", b =>
                {
                    b.Property<Guid>("Registration_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Registration_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ticket_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Registration_ID");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Property<Guid>("Terminal_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Gate_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal_Nr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Terminal_ID");

                    b.HasIndex("Gate_ID");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Aircraft", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", null)
                        .WithMany("Aircrafts")
                        .HasForeignKey("Flight_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airline", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", null)
                        .WithMany("Airlines")
                        .HasForeignKey("Flight_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airport", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Airline", null)
                        .WithMany("Airports")
                        .HasForeignKey("Airline_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Terminal", null)
                        .WithMany("Airports")
                        .HasForeignKey("Terminal_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", null)
                        .WithMany("Employees")
                        .HasForeignKey("Terminal_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.FlightStatus", "FlightStatus")
                        .WithMany()
                        .HasForeignKey("FlightStatus_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightStatus");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Flight", null)
                        .WithMany("Gates")
                        .HasForeignKey("Flight_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Passanger", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Baggage", null)
                        .WithMany("Passangers")
                        .HasForeignKey("Baggage_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Flight", null)
                        .WithMany("Passangers")
                        .HasForeignKey("Flight_ID");

                    b.HasOne("DatabaseTask.Core.Domain.Registration", null)
                        .WithMany("Passangers")
                        .HasForeignKey("Registration_ID1");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Gate", null)
                        .WithMany("Terminals")
                        .HasForeignKey("Gate_ID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Airline", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Baggage", b =>
                {
                    b.Navigation("Passangers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flight", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("Airlines");

                    b.Navigation("Gates");

                    b.Navigation("Passangers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Gate", b =>
                {
                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registration", b =>
                {
                    b.Navigation("Passangers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Navigation("Airports");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
